# Generated by Django 3.2.6 on 2021-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210917_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pictures'),
        ),
    ]
